version: '3'

services:

  # ===================
  #      Minecraft
  # ===================
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565/tcp"
      - "25565:25565/udp"
    environment:
      EULA: "TRUE"
      RCON_PASSWORD: "7355608"
      TYPE: KETTING
      VERSION: "1.20.1"
      MEMORY: 6G
    depends_on:
      restore-backup:
        condition: service_completed_successfully
    volumes:
      - ./mc-data:/data

  # ===================
  #       Backups
  # ===================
  restore-backup:
    image: itzg/mc-backup # Same image as mc, but any base image with bash and tar will work
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      - ./mc-data:/data # Must be same mount as mc service, needs to be writable
      - ./mc-backups:/backups:ro # Must be same mount as backups service, but can be read-only
  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "6h"
      RCON_HOST: mc
      INITIAL_DELAY: 0 # since this service waits for mc to be healthy, no initial delay is needed
      PRE_BACKUP_SCRIPT: |
        echo "Backup time!"
        echo "Backup from $$RCON_HOST to $$DEST_DIR"
      POST_BACKUP_SCRIPT_FILE: /post-backup.sh # Add github support
    volumes:
      - ./mc-data:/data:ro
      - ./mc-backups:/backups

  # ===================
  #   Monitoring stuff
  # ===================
  # May cause high memory usage, try disabling this 
  # things IF the server has some performance issues
  monitor:
    image: itzg/mc-monitor
    command: export-for-prometheus
    environment:
      EXPORT_SERVERS: mc
      DEBUG: "true"
    depends_on:
      - mc
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    ports:
      - "8180:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-tsdb:/prometheus
    depends_on:
      - monitor
  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-8.3.3}
    ports:
      - "3000:3000"
    volumes:
      - grafana-lib:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus

  # ====================
  #       Web Rcon
  # ====================
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: mc # is referring to the service name 'mc' declared below
      RWA_RCON_PASSWORD: "7355608" # needs to match the password configured for the container, see RCON_PASSWORD below
    ports:
      - "4326:4326"
      - "4327:4327"

volumes:
  mc-data: {}
  prometheus-tsdb: {}
  grafana-lib: {}